jhuntwork/merelinux

packages/pacman/ChangeLog
packages/pacman/PKGBUILD
packages/pacman/dependencies.sh
packages/pacman/std-build-functions.sh

Add some functions which can be used in PKGBUILD as helper
functions to avoid a lot of repetition in the PKGBUILD files.
Also improve dependencies.sh based on feedback from shellcheck

[pacman] Add some standard build functions

---

packages/binutils/ChangeLog
packages/binutils/PKGBUILD

There still seem to be issues with some packages using gold with
musl and bfd is satisfactory for now.

[binutils] Move back to bfd as the default linker

---

dev.Dockerfile
scripts/build-in-docker.sh

This will make it easier to execute a build inside docker in a
consistent way.

Add a convenience script to mere/dev image

---

.circleci/config.yml
scripts/build.sh
scripts/ci-build.sh
scripts/ci-upload.sh

* Use mere/dev in circle-ci pipeline config
* Use mere/dev and docker for local builds

Adjust building methods to consistently use Docker

---

.gitignore
packages/libressl/ChangeLog
packages/libressl/PKGBUILD

[libressl] Fix missing ca-certs path

---

packages/linux-headers/ChangeLog
packages/linux-headers/PKGBUILD

The linux-headers as part of the system toolchain can be separate from
the running kernel. Track them separately for easier packaging and
build requirements.

[linux-headers] Use a separate PKGBUILD

---

packages/dropbear/ChangeLog
packages/dropbear/PKGBUILD

Also remove 'ssh' and 'scp' symlinks, since these will conflict with
openssh-client, which is needed for some specific features in the
pipelines, and no doubt, elsewhere. Should find a way to support
alternatives.

[dropbear] Upgrade to 2020.81

---

packages/busybox/ChangeLog
packages/busybox/PKGBUILD

`telinit` is just a shell script that will invoke certain s6 specific
tools to initiate system shutdown. Because it is so specific to s6, it
makes sense to ship with that package.

[busybox] Remove telinit, it is moving to s6

---

packages/shellcheck/ChangeLog
packages/shellcheck/PKGBUILD

Upstream already builds a static binary and that's all we need for now.

[shellcheck] Upgrade to 0.7.1

---

packages/llvm/ChangeLog
packages/llvm/PKGBUILD

* The linux kernel build system expects llvm-strip
* Building for the native target only reduces the package size by around
half its current size

[llvm] Add llvm-strip and build for native only

---

packages/acl/ChangeLog
packages/acl/PKGBUILD

In the process of defining 'core' and 'core-dev' groups. Will evaluate
additional groups in the future

[acl] Remove from groups for now

---

packages/base-layout/PKGBUILD
packages/base-layout/profile
packages/linux-headers/ChangeLog
packages/linux-headers/PKGBUILD
packages/llvm/ChangeLog
packages/llvm/PKGBUILD
packages/musl/ChangeLog
packages/musl/PKGBUILD

Mere started out without using /usr for much, on the basis that /usr
is a historical artifact that has no particular meaning. The experiment
worked well, but going forward, it appears that /usr is still expected
and comfortable for most people, there are a few workarounds that we
have to do to ignore it (technically it still existed anyway) and the
benefits of doing so are minimal at best.
Avoid unnecessarily suprising new users by keeping /usr as the main
installation prefix.

Update toolchain and base-layout to use /usr

---

packages/openssl/ChangeLog
packages/openssl/PKGBUILD

Also:
- Use /usr for prefix
- Remove from any groups - Related to #128
- Set provides for lib dependencies

[openssl] Upgrade to 1.1.1k

---

packages/curl/ChangeLog
packages/curl/PKGBUILD

- Use openssl instead of libressl
- Add to new core group
- Use /usr for prefix
- Add provides for libcurl.so.4

[curl] Updates

---

packages/pacman/ChangeLog
packages/pacman/PKGBUILD
packages/pacman/dependencies.sh
packages/pacman/makepkg.conf

- Switch to /usr prefix (keep /bin dir for binaries)
- Add to new core group; Related to #128
- Update dependencies.sh to detect library names instead of package
names
- Update makepkg.conf to use /usr for dirs and /usr/bin/curl for pkg
fetching
- Use openssl instead of libressl

[pacman] Updates

---

packages/libffi/ChangeLog
packages/libffi/PKGBUILD

- Remove from any groups; Related to #128
- Use /usr for prefix
- Add lib provides

[libffi] Updates

---

Dockerfile
dev.Dockerfile
scripts/build-in-docker.sh
scripts/build.sh

- Updates to recent versions of packages from the testing channel
- Makes `scripts/build.sh` slightly more portable. For example, pending
release of the next version of docker with fixes like
[this one](https://github.com/moby/moby/pull/42054), it should be
possible to build mere packages on Mac hosts.
- Use a non-privileged user in the container and map that user to the
uid and gid of the host system user so that created files in the
mounted volumes will be owned by the host user.

Improvements to build scripts and containers

---

scripts/build.sh

The format string only expects one value, but two were passed.

Fix addition of group line for build.sh

---

packages/pacman/ChangeLog
packages/pacman/PKGBUILD
packages/pacman/makepkg.conf

- Replace -O2 with -Os in default CFLAGS. Some very basic benchmark
tests show that with clang -Os reduces some size but doesn't include a
noticeable performance drop. -Oz can reduce size even further, but
then there is a minor performance hit. It seems safe to use -Os as a
default
- Also don't hard code the architecture. In the future, will likely want
to support at least some arm archs.

[pacman] Updates to makepkg.conf

---

.circleci/config.yml

Docker itself was fixed a while ago, if circleci has updated the
builds should work as defined.

Turn on circleci builds again to test

---

packages/cmake/ChangeLog
packages/cmake/PKGBUILD
scripts/build.sh
scripts/ci-build.sh
scripts/ci-upload.sh

Pipeline jobs from pull requests will already build and test packages.
We can avoid building them again on master then, if we can save the archives
from successful pipelines.
Bump the cmake version so we can fully test the pipelines

Updates to ci-upload script

---

scripts/ci-upload.sh

Install the temporary pacman to /tmp first, then use it to install
pacman-build (and pacman again) to the local directory, avoiding the
--overwrite flag which seems to not work as expected on first use.

Fix bug in master pipeline upload stage

---

scripts/ci-upload.sh

Instead of `aws s3 sync --delete` with a local empty directory. This
should be more explicit and catch all cases.

Use `aws s3 rm --recursive`

---

packages/git/ChangeLog
packages/git/PKGBUILD

Also:
- Use openssl
- Remove from groups for the moment
- Switch prefix to /usr

[git] Upgrade to 2.32.0

---

scripts/ci-upload.sh

Something about running this command in the pipeline is causing it to
appear to succeed, but not actually do anything. Testing a sleep to see
if that changes anything.

Sleep after calling `aws s3 rm`

---

scripts/ci-upload.sh

The previous sleep was unnecessary - there was a typo on the path

Fix the `aws s3 rm` issue

---

packages/curl/ChangeLog
packages/curl/PKGBUILD

Also:
- Generate ca-certificates from mk-ca-bundle
- Move the ca-certs package to curl from libressl

[curl] Upgrade to 7.78.0

---

scripts/build.sh

realpath_cd was printing out the directory that was changed to when
calling `cd -` in addition to the output from `pwd -P`.
Also adding -x to the top of the script for gathering info about the
pipeline environment. The docker builds need to be done with at least a
fake root account so that permissions in the generated packages are
correct. So this begins and investigation into the correct solution
there.

Fix bug in build.sh

---

scripts/build.sh

Just use a variable to reference the function or command instead.
Also add some missing newlines.

Remove use of alias in build.sh

---

packages/fedup/ChangeLog
packages/fedup/PKGBUILD

This small utility will be used with pacman-build to de-duplicate files
in packages by creating hard links.

[fedup] Initial version

---

buildpkg.sh
ci-scripts/ci-upload.sh
packages/pacman/pacman-dev.conf

Refs #166
This will avoid naming conflicts with stable, allowing a developer to
have both repositories enabled on a single machine.
Will continue to evaluate repository layou and shape, using
https://wiki.archlinux.org/index.php/official_repositories as a source
of inspiration.

Rename the testing db from main to testing

---

dev-scripts/gen_changelog

Adjust the script to produce a new changelog format. It doesn't seem
important to list a maintainer email in each entry. Instead, the main
entry should be primarily tied to a release version and the date can be
included for reference. The new format will look like:
```txt
1.2.3-1 (2021-08-29)
This is a log message indicating a change.
This is another change.
Changes could also be listed as:
- Change 1
- Change 2
```
The script will first reformat an existing ChangeLog, and then attempt
to prompt for and add a new entry if one doesn't exist for the package version
and release combination.

Refactored the gen_changelog script

---

buildpkg.sh
dev-scripts/gen
dev-scripts/gen_changelog

Challenges:
- Building as a non-root user will create packages with incorrect
permissions
- Buiding as root with the in-tree packages directory will leave
root-owned files and directories in the git-managed tree
- Scripts to calculate sums and generate changelogs require tools that
may not be present on the host system and can easily be managed in the
development container, so it's nicer to run them there. However,
running as root will again create or modify files as the root user and
can cause permission issues for the git-managed tree.
Decisions:
- For the special dev-scripts actions, auto-generating sums and
changelogs, run as an unprivileged user with the current tree mounted.
This will make changes with the current user's uid/gid and operate on
the git-managed files.
- For other …

Refactor buildpkg.sh for the sake of permissions

---

dev-scripts/build-in-docker

In the build-in-docker script, after upgrading, some previous paths may
have changed. busybox's sh appears to cache paths it finds. Clear the
paths explicitly to avoid potential 'not found' issues if binary paths
have changed during upgrades.

Excplicitly clear the shell's path cache via hash

---

dev-scripts/gen_changelog
packages/mksh/ChangeLog
packages/mksh/PKGBUILD

Also adjust the version regex in gen_changelog to support mksh's
verisons.

[mksh] Move man page to /usr/share/man

---

packages/ncurses/ChangeLog
packages/ncurses/PKGBUILD

Some code looks for an ncursesw directory, so satisfy it via symlinks.
The previous symlink was broken as the headers had been installed
directly in the /usr/include directory, instead of /usr/include/ncurses

[ncurses] Fix ncursesw headers

---

packages/ncurses/ChangeLog
packages/ncurses/PKGBUILD

It needs to include existing symlinks

[ncurses] Fix find command for headers

---

packages/kpartx/ChangeLog
packages/kpartx/PKGBUILD

Also:
- Remove from base group
- Install binaries to /usr/sbin
- Add man page for kpartx

[kpartx] Upgrade to 0.8.6

---

packages/gptfdisk/ChangeLog
packages/gptfdisk/PKGBUILD

Also:
- Remove from base group
- Install binaries to /usr/sbin instead of /bin
- Add man pages

[gptfdisk] Upgrade to 1.0.8

---

dev.Dockerfile

Using build-base instead. The term 'core' will be used for the main
repository housing the foundation software for Mere Linux. 'base' is
a group of the packages required for all Mere systems, and 'build-base'
is a group of the most common development tools required for compiling
most packages.
Resolves #166

Remove last reference to core-dev

---

packages/llvm/ChangeLog
packages/llvm/PKGBUILD

readelf wasn't shipped before, but some tools make use of it.
Specifically, makepkg now uses it for file type information when
choosing how to strip symbols from files

[llvm] Build and package readelf

---

packages/pacman/ChangeLog
packages/pacman/PKGBUILD
packages/pacman/dependencies.sh

Normalize the libc.so dependency to use the ld-musl-$(arch).so.1 name
instead.

[pacman] Fix dependency checking

---

buildpkg.sh
dev-scripts/build-in-docker

If the SIGNING_KEY env variable is set, use that as a gpg secret key for
signing packages and repositories.
Fixes #7
Will still need to go through and sign all packages and then set the
default pacman configuration for stable/testing to require signatures.

Adjust build scripts to sign packages/repo

---

.circleci/config.yml
buildpkg.sh
dev-scripts/build-in-docker
packages/pacman/ChangeLog
packages/pacman/PKGBUILD

For now, there are too many base system dependencies when using pacman's
gpg implementation. It requires gpg and friends to be installed on the
system as well as bash and bash libs for pacman-key. Digital signing
will be looked at through other mechanisms
See this comment: https://github.com/jhuntwork/merelinux/issues/7#issuecomment-916926986

[pacman] Back out gpg support

---

packages/binutils/ChangeLog
packages/binutils/PKGBUILD

binutils is needed by gcc, which is needed to build syslinux
Related to #237

[binutils] Re-add at 2.37

---

packages/syslinux/ChangeLog
packages/syslinux/PKGBUILD

Also:
- Remove some unused headers/libs
- Remove from base group
- Remove dependency on perl, while keeping some rarely used perl scripts
shipped with the package
Fixes #237

[syslinux] Re-package, building with gcc-9.4

---

packages/musl/ChangeLog
packages/musl/PKGBUILD

The utmps package will provide utmpx, so remove the header and lib
symbols and adjust utmp paths to point at ones utmps will
provide/support.

[musl] Remove utmpx support

---

packages/s6/ChangeLog
packages/s6/PKGBUILD
packages/s6/mdevd-service
packages/s6/rc.init

Remove the mdevd service file and configuration. Those will be added to
the mdevd package in a future commit. This follows a similar pattern as
the utmps package and allows mdevd to be optionally installed, in case a
user wishes to run without kernel modules.
Also adjust the call to mdevd-coldplug to wait until mdevd has signaled
that it is up

[s6] Adjust mdevd configuration

---

packages/sudo/ChangeLog
packages/sudo/PKGBUILD

The static binary is segfaulting. Likely to do with its insistence on
supporting dynamic plugins

[sudo] Build dynamic binary again

---

packages/sudo/ChangeLog
packages/sudo/PKGBUILD

Switching from static binary to shared requires building and shipping
the internal dynamic libs as well

[sudo] Add missing libs

---

packages/pacman/ChangeLog
packages/pacman/PKGBUILD
packages/pacman/dependencies.sh

Instead of trying to collect the dependencies in a variable that
mutates during loops, output all dependencies to a temporary file and
then sort it at the end.

[pacman] Fix some subtle bugs in dependencies.sh

---

packages/utmps/ChangeLog
packages/utmps/PKGBUILD

Allow the service dirs to be world readable

[utmps] Remove utmps-dev from the base group

---

packages/musl/ChangeLog
packages/musl/PKGBUILD

Things that should be using utmp should be talking to utmps via its
client library and the running utmps service. Everything else that is
falling back to utmp.h and standard lib should really be going to
/dev/null (the default musl path) as insecure

[musl] Leave the default utmp paths alone

---

packages/e2fsprogs/ChangeLog
packages/e2fsprogs/PKGBUILD

These will be provided via the util-linux source. That version of blkid
includes a feature to list PARTUUIDs, helpful with gpt partitions.

[e2fsprogs] Remove blkid, libblkid and libuuid

---

ci-scripts/ci-upload.sh

More recent versions are using /usr/bin instead of /bin

Fix path in ci scripts of pacman binary

---

ci-scripts/ci-upload.sh

It appears to be no longer needed, fixed upstream

Remove a modification in the ci-scripts to repo-add

---

INSTALLING.md
README.md

And update the main README to point to it. Also add a brief snippet
about available docker containers.
Fixes #362

Add initial installation instructions

---

packages/skalibs/ChangeLog
packages/skalibs/PKGBUILD

Effectively just moves the headers to /usr/include instead of the
odd /include directory

[skalibs] Adjust paths

---

packages/llvm/0001-add-readelf.patch
packages/llvm/ChangeLog
packages/llvm/PKGBUILD

Move the LTO lib to the main llvm package, rename llvm-runtime-libs to
libcxx, which is more accurate

[llvm] Fix packaging issue with libs

---

packages/libmilter/ChangeLog
packages/libmilter/PKGBUILD

More information found in the alpine patch:
https://git.alpinelinux.org/aports/tree/main/libmilter/default-pthread-stacksize.patch

[libmilter] Fix a bug in the pthread stack size

---

README.md

A core mailing list has been set up for generic Mere Linux discussions
using mlmmj and hypermail.
Fixes #10

Add notes about Mere Mailing Lists

---

dev-scripts/build-in-docker
dev-scripts/gen_sums
dev.Dockerfile

It's unneeded and makes it less flexible due to dynamic dependencies on specific versions of skalibs

Remove sudo from dev environment

---

packages/openssh/ChangeLog
packages/openssh/PKGBUILD

For the sake of circleci/github integration

openssh: Revert to 8.7

---

packages/llvm/ChangeLog
packages/llvm/PKGBUILD

The shared libclang library is required by firefox
Also separate libunwind from libcxx as its own package

llvm: Add libclang as its own package

---

.circleci/config.yml
buildpkg.sh
ci-scripts/ci-build.sh
dev-scripts/aa-distcc.sh

When using a branch name ending in -parallel, launch multiple build
machines that can use distcc together for increased build times.

Adjust CI to support some parallel builds

---

buildpkg.sh
ci-scripts/ci-build.sh
packages/llvm/ChangeLog
packages/llvm/PKGBUILD

And call Ninja directly, add variables to control parallel build jobs

llvm: Add llvm-strip
