jhuntwork/merelinux

.circleci/config.yml
packages/binutils/ChangeLog
packages/binutils/PKGBUILD
packages/binutils/PKGTEST
scripts/ci-build.sh
scripts/ci-setup.sh
scripts/ci-test.sh
scripts/ci-upload.sh

Also test building in the pipeline

[binutils] Build binutils with bfd linker

---

packages/attr/ChangeLog
packages/attr/PKGBUILD

[attr] Use standard build functions

---

packages/autoconf/ChangeLog
packages/autoconf/PKGBUILD

[autoconf] Use standard build functions

---

packages/bash/ChangeLog
packages/bash/PKGBUILD

And use standard build functions

[bash] Upgrade to 5.0.7

---

packages/acl/ChangeLog
packages/acl/PKGBUILD
scripts/ci-build.sh

Use acl package for testing in pipeline

Generate source packages too

---

packages/bison/ChangeLog
packages/bison/PKGBUILD

Also use standard build functions and add a check stage

[bison] Upgrade to 3.4.1

---

packages/libressl/ChangeLog
packages/libressl/PKGBUILD

Also use a more standard path for CA certificates.

Upgrade libressl to 3.2.4

---

packages/curl/ChangeLog
packages/curl/PKGBUILD

Also use a more common CA certificates path

[curl] Upgrade to 7.75.0

---

packages/gptfdisk/ChangeLog
packages/gptfdisk/PKGBUILD

And build with musl 1.2.2, and latest popt and libuuid

[gptfdisk] Upgrade to 1.0.6

---

packages/libaio/ChangeLog
packages/libaio/PKGBUILD

[libaio] Initial version at 0.3.112

---

packages/attr/ChangeLog
packages/attr/PKGBUILD

[attr] Remove from any groups for now

---

packages/autoconf/ChangeLog
packages/autoconf/PKGBUILD

[autoconf] Add to new core-dev group

---

packages/automake/ChangeLog
packages/automake/PKGBUILD

[automake] Add to new core-dev group

---

packages/base-layout/ChangeLog
packages/base-layout/PKGBUILD
packages/base-layout/shells

Also add /bin/sh to /etc/shells
Related to #128

[base-layout] Add to new core group

---

packages/bc/ChangeLog
packages/bc/PKGBUILD

[bc] Remove from any groups for now

---

packages/bison/ChangeLog
packages/bison/PKGBUILD

[bison] Add to new core-dev group

---

packages/build-essential/ChangeLog
packages/build-essential/PKGBUILD

[build-essential] Add to new core-dev group

---

packages/libarchive/ChangeLog
packages/libarchive/PKGBUILD
packages/nettle/ChangeLog
packages/nettle/PKGBUILD

[nettle] Remove from any groups and set prefix to /usr

---

packages/m4/ChangeLog
packages/m4/PKGBUILD

[m4] Add to core-dev group and use /usr prefix

---

packages/make/ChangeLog
packages/make/PKGBUILD

[make] Add to core-dev group and use /usr for prefix

---

packages/patch/ChangeLog
packages/patch/PKGBUILD

[patch] Add to core-dev group and use /usr for prefix

---

packages/perl/ChangeLog
packages/perl/PKGBUILD

[perl] Remove from any group and set prefix to /usr

---

packages/pkgconf/ChangeLog
packages/pkgconf/PKGBUILD

[pkgconf] Add to core-dev group and set prefix to /usr

---

packages/ncurses/ChangeLog
packages/ncurses/PKGBUILD

[ncurses] Remove from any groups and set prefix to /usr

---

packages/musl/ChangeLog
packages/musl/PKGBUILD

Also move libs back to /lib while keeping include files in /usr/include

[musl] Add libc.so to provides

---

packages/readline/ChangeLog
packages/readline/PKGBUILD

- Remove from any groups; Related to #128
- Set prefix to /usr
- Define library provides

[readline] Updates

---

packages/python/ChangeLog
packages/python/PKGBUILD

- Use openssl instead of libressl
- Remove any groups for now; Related to #128
- Set prefix to /usr

[python] Updates

---

.circleci/config.yml
packages/cmake/ChangeLog
packages/cmake/PKGBUILD
scripts/ci-build.sh
scripts/ci-setup.sh
scripts/ci-upload.sh

[cmake] Use openssl instead of libressl

---

scripts/ci-build.sh
scripts/ci-upload.sh

We can use packages build in pull request pipelines

Don't build packages on master pipeline

---

scripts/ci-upload.sh

Also empty the local staging directory to clean out the upstream one

Fix destination dir when syncing src files

---

packages/execline/ChangeLog
packages/execline/PKGBUILD

Also:
- Add package to core group. Refs #128

[execline] Upgrade to 2.8.0.1

---

scripts/ci-upload.sh

This should avoid tainting pipelines with work from other pipelines

Use PR-specific upload paths for CI jobs

---

packages/base-layout/ChangeLog
packages/base-layout/PKGBUILD
scripts/ci-upload.sh

And bump release on base-layout since it didn't publish on last merge.

Fix a bug in ci-upload.sh

---

packages/curl/ChangeLog
packages/curl/PKGBUILD

[curl] Remove from core group

---

scripts/ci-upload.sh

This will allow to remove old packages

Sync down testing pkgs before uploading

---

packages/mksh/ChangeLog
packages/mksh/PKGBUILD

[mksh] Add to core group

---

packages/s6/ChangeLog
packages/s6/PKGBUILD
packages/s6/mdevd-service
packages/s6/rc.init

[s6] Use mdevd for kernel coldplug events

---

scripts/ci-upload.sh

Ensure it's never empty in a branch pipeline

Extra test to catch the PR number

---

packages/s6/ChangeLog
packages/s6/PKGBUILD

The last one failed to upload in the pipeline correctly

[s6] Triggering a new release

---

CONTRIBUTING.md
README.md
template.PKGBUILD

And a template PKGBUILD file as a starting point for new packages

Add an initial CONTRIBUTING document

---

packages/sudo/ChangeLog
packages/sudo/PKGBUILD

[sudo] Upgrade to 1.9.7p2

---

packages/file/ChangeLog
packages/file/PKGBUILD

[file] Upgrade to 5.40

---

packages/gettext/ChangeLog
packages/gettext/PKGBUILD

Remove static flags, not as important with this package

[gettext] Move to /usr prefix

---

packages/libdevmapper/ChangeLog
packages/libdevmapper/PKGBUILD

[libdevmapper] Upgrade to 2.03.13

---

packages/pcre/ChangeLog
packages/pcre/PKGBUILD

[pcre] Upgrade to 8.45

---

packages/strace/ChangeLog
packages/strace/PKGBUILD

[strace] Upgrade to 5.13

---

packages/openssh/ChangeLog
packages/openssh/PKGBUILD

[openssh] Upgrade to 8.7p1

---

packages/nginx/99-default
packages/nginx/ChangeLog
packages/nginx/PKGBUILD
packages/nginx/nginx-service
packages/nginx/nginx.install

[nginx] Upgrade to 1.21.1

---

packages/go/ChangeLog
packages/go/PKGBUILD

[go] Upgrade to 1.17

---

packages/vim/ChangeLog
packages/vim/PKGBUILD

[vim] Upgrade to 8.2.3354

---

packages/mdevd/ChangeLog
packages/mdevd/PKGBUILD

After missing the ci release pipeline

[mdevd] Re-release latest version

---

packages/linux/ChangeLog
packages/linux/PKGBUILD

Remove from base group, add to core

[linux] Upgrade to 5.10.61

---

packages/gptfdisk/ChangeLog
packages/gptfdisk/PKGBUILD

The previous release intended to do this, but missed it

[gptfdisk] Remove from base group

---

packages/pciutils/ChangeLog
packages/pciutils/PKGBUILD

[pciutils] Upgrade to 3.7.0

---

packages/base-layout/ChangeLog
packages/base-layout/PKGBUILD
packages/base-layout/profile

- Update /etc/profile with improved prompt and to set TERM
- Move from core group to base group
Related to #166

[base-layout] Version 2.0.4

---

packages/busybox/ChangeLog
packages/busybox/PKGBUILD

[busybox] Move from core group to base group

---

packages/pkgconf/ChangeLog
packages/pkgconf/PKGBUILD

Also move from core-dev group to build-base group
Related to #166

[pkgconf] Upgrade to 1.8.0

---

packages/patch/ChangeLog
packages/patch/PKGBUILD

[patch] Move from core-dev group to build-base group

---

packages/pacman/ChangeLog
packages/pacman/PKGBUILD
packages/pacman/pacman-dev.conf
packages/pacman/pacman.conf

Also update pacman.conf to use the core repo
Related to #166

[pacman] Move from core group to base group

---

packages/musl/ChangeLog
packages/musl/PKGBUILD

[musl] Move from core-dev group to build-base group

---

packages/mksh/ChangeLog
packages/mksh/PKGBUILD

[mksh] Move from core group to base group

---

packages/make/ChangeLog
packages/make/PKGBUILD

[make] Move from core-dev group to build-base group

---

packages/m4/ChangeLog
packages/m4/PKGBUILD

Also move from core-dev group to build-base group
Related to #166

[m4] Upgrade to 1.4.19

---

packages/llvm/ChangeLog
packages/llvm/PKGBUILD

[llvm] Move from core-dev group to build-base group

---

.circleci/config.yml
ci-scripts/ci-build.sh
dev-scripts/build-in-docker
packages/libgpg-error/ChangeLog
packages/libgpg-error/PKGBUILD

[libgpg-error] Re-build to sign

---

.circleci/config.yml
dev-scripts/build-in-docker

Had to remove them temporarily while the testing repo had a signed
package in it

Perform upgrades again

---

packages/shellcheck/ChangeLog
packages/shellcheck/PKGBUILD

[shellcheck] Upgrade to 0.7.2

---

packages/mdevd/ChangeLog
packages/mdevd/PKGBUILD
packages/mdevd/mdev.conf
packages/mdevd/mdevd-service
packages/mdevd/mdevd.install

Also:
- Add to the base group
- Add dependency on s6, execline
- Adjust the libudev-zero events to go to /run/.libudev-zero

[mdevd] Add the service file here instead of in s6

---

packages/utmps/ChangeLog
packages/utmps/PKGBUILD
packages/utmps/utmps.install

- No need to manage user/group since they ship with base-layout
- Add a dependency on s6

[utmps] Simplify install hooks

---

packages/busybox/ChangeLog
packages/busybox/PKGBUILD
packages/busybox/initramfs-init
packages/busybox/mkinitramfs

Not sure exactly if this is the best package for these utilities, but
adding them to their own seemed a bit overkill. Adding to busbox for
now, can review in the future as needed.

[busybox] Add scripts for creating an initramfs

---

packages/dropbear/ChangeLog
packages/dropbear/PKGBUILD

[dropbear] Rebuild with latest musl, utmps, skalibs

---

buildpkg.sh
ci-scripts/ci-upload.sh

- One more fix to ci-upload to find the right makepkg libs
- Explicitly set the working dir for buildpkg.sh

script fixes

---

ci-scripts/ci-upload.sh

Also adjust the installation path of other tools installed

Install static curl with known features in ci-upload.sh

---

ci-scripts/ci-upload.sh
packages/libevent/PKGBUILD

Also a minor change in libevent/PKGBUILD to trigger another build

More verbosity in ci-upload.sh script

---

misc-util/disk_image
misc-util/livecd

- Updates disk_image to use an initramfs to auto-resize
- Adds a livecd script to generate a bootable ISO image

Update image creation scripts

---

packages/opendkim/ChangeLog
packages/opendkim/PKGBUILD
packages/opendkim/opendkim-log

[opendkim] Re-build against fixed libmilter

---

Dockerfile
dev.Dockerfile

- Add ca-certs to mere/base
- Add perl to mere/dev (and update to latest llvm with mold)

Update docker images

---

packages/pacman/0001-libalpm-Add-support-for-asignify-signatures.patch
packages/pacman/0002-Add-a-configuration-option-for-asignify-s-key-dir.patch
packages/pacman/0003-Add-documentation-for-the-AsignifyDir-option.patch
packages/pacman/0004-Update-meson-for-asignify.patch
packages/pacman/0005-Modify-makepkg-to-use-asignify.patch
packages/pacman/ChangeLog
packages/pacman/PKGBUILD
packages/pacman/pacman-dev.conf

Uses asignify to sign and validate

pacman: Add support for package signatures

---

ci-scripts/ci-setup.sh
packages/busybox/ChangeLog
packages/busybox/PKGBUILD

busybox: Upgrade to 1.33.2

---

packages/acl/PKGBUILD

Need a no-op change to trigger a package rebuild in the pipeline

acl: trigger rebuild

---

ci-scripts/ci-upload.sh
packages/acl/PKGBUILD

And fix key rendering for main branch upload stage

acl: trigger build again

---

packages/autoconf/ChangeLog
packages/autoconf/PKGBUILD

Trigger a rebuild which will sign the package

autoconf: Sign package

---

packages/git/ChangeLog
packages/git/PKGBUILD

Also add the Git perl module. Fixes #379

git: Upgrade to 2.37.3

---

packages/llvm/ChangeLog
packages/llvm/PKGBUILD

Also, re-add libgcc_s symlinks to libunwind. Rust requires this.

llvm: Upgrade to 15.0.6
